import pandas as pd
from pathlib import Path

def json2cleandf(path: Path):
    """Takes path to JSON data generated by the consumer and returns pandas dataframe containing the columns 
    in the Lasair filter that generated the JSON, plus the columns from the diaSource table (Rubin Schema) for 
    the latest diaSourceId. 

    This is a cleaning step before feature csv files can be created in the pyplines.

    Parameters
    ----------
    path: Path
        Path to the json file 

    Returns
    -------
    pd.DataFrame
    list
    """

    # 1. Load the whole JSON into a dataframe. 
    #    There are nested levels in the 'alert' column (which we will take care of)""
    #    'diaObject', 'diaSourcesList', 'diaForcedSourcesList', 'diaNondetectionLimitsList', 'annotations', 'ebv'
    json_df = pd.read_json(path)

    # 2. Make the latest_source_df 
    #    diaSourceList contains the diaSource table fields for each diaSource in a given diaObject/row
    #    the latest source is the last item. The easiest thing to do is extract the 1-row dataframe of the last source
    #    for each diaObjectId and collect them in a list to cocatenate at the end
    #    WARNING: CONCATENATION OF DATAFRAMES IN A LOOP IS SLOWER THAN THIS (because copies have to be made every time)

    latestSourceId_dfList = []
    objectIds_withoutAlert_col = []
    for i in range(json_df.shape[0]):
        try: 
            latestSourceId_dfList.append(pd.DataFrame(json_df['alert'].values[i]['diaSourcesList'][-1], 
                                                index=[0]))
        except TypeError:
            # this happens if the alert column for that row is NaN
            # if that happens, we have a problem and we need to log it
            objectIds_withoutAlert_col.append(json_df['diaObjectId'].values[i])


    # 3. Concatenate and set the index
    latestSourceIds_df = pd.concat(latestSourceId_dfList)
    latestSourceIds_df.set_index('diaObjectId', inplace=True)

    # 4. Make the filter output df
    #    Take all rows (axis=0), and every column (axis=1) except the last one ('alert')
    filterOutput_df = json_df.iloc[:,:-1]
    filterOutput_df.set_index('diaObjectId', inplace=True)

    # 5. Join!
    clean_df = latestSourceIds_df.join(filterOutput_df, lsuffix='_sourceId')

    return clean_df.reset_index(), objectIds_withoutAlert_col

