"""
Docstring for lvra.utils.features

Dev Notes on json2cleandf indexing fuckery
--------------------------------------------

The function json2cleandf takes a json file and generates a neat feature data frame. 
To do so it has to navigate the JSON data which contains:
- The lasair filter outputs in the first level. That is indexed by diaObjectId as per Lasair Schema.
- The latest diaSourceId data which is nested in ['alert']['diaSourcesList'] and is the last item 
of that list. That is indexed by diaSourceId as per Rubin Schema.

Here is the fun part: 
- Sometimes the same diaObjectId has multiple instances of data in the JSON file because several 
alerts arrived within the hour. Then the diaObjectId for our filter output data is not unique, 
and multiple latest diaSourceIds"point" to the same diaObjectId.
- Sometimes the alert column is NaN. So some diaObjectIds don't have that latest diaSourceId 
data at all. 

Today (2026-02-10), when looking at the output of my function I was getting these fun shapes:

> latestSourceIds_df.diaSourceId.unique().shape, latestSourceIds_df.diaObjectId.unique().shape
((41,), (40,))

> filterOutput_df.shape, filterOutput_df.diaObjectId.unique().shape
((82, 23), (40,))

In the latestSourceIds dataframe with have an extra source because I guess our alert batch 
there contained two separate source alerts for a given diaObject (as mentioned above)
then we have our filter output, which has more rows than unique objects... 
**This is weird and unexpected - do we have some repeats in the stream again?**

Even if the stream is working imporperly, I can't have my code fall apart because kafka is 
confused. So I needed to fix this.

The Goal: BE ABLE TO JOIN MY DATAFRAMES WITH A PROPER INDEX

The Solution: KEEP TRACK OF THE NUMBER OF MY LOOP USING loop_index. 
By incrementing it also when there is a failure due to a missing ['alert'] field, I make sure
that the index of my feature dataframes are NOT SEQUENTIAL BUT UNIQUE AND LINED UP properly. 

"""
import pandas as pd
from pathlib import Path
import numpy as np

mag_to_njy_thresholds = {'23': 2_291, 
                         '22': 5_754, 
                         '21': 14_454, 
                         '20': 36_309, 
                         '19': 91_201, 
                         '18': 229_086,
                         '17': 574_340,
                         }

def flux_threshold_features(df_lc, threshold_njy):
    """lc_df must at least contain the columns psfFlux and midpointMjdTai"""

    n_above = (df_lc['psfFlux']>threshold_njy).sum()
    is_above_flag = None
    first_time_flag = None

    if n_above ==1 and np.isclose(df_lc[df_lc['psfFlux']>threshold_njy].midpointMjdTai.max(), 
                                                                   df_lc.midpointMjdTai.max()):
        # This is the first time this alert passed the threshold
        is_above_flag = True
        first_time_flag = True
    elif n_above >= 1:
        # Not the first alert above threshold
        # Or one alert only passes the threshold but it was an older one
        is_above_flag = True
        first_time_flag = False
    elif n_above == 0:
        # No alert above threshold
        is_above_flag = False
        first_time_flag = False


    return is_above_flag, first_time_flag, int(n_above)


def json2cleandf(path: Path):
    """Takes path to JSON data generated by the consumer and returns pandas dataframe containing the columns 
    in the Lasair filter that generated the JSON, plus the columns from the diaSource table (Rubin Schema) for 
    the latest diaSourceId. 

    This is a cleaning step before feature csv files can be created in the pyplines.

    Parameters
    ----------
    path: Path
        Path to the json file 

    Returns
    -------
    pd.DataFrame
    list
    """

    # 1. Load the whole JSON into a dataframe. 
    #    There are nested levels in the 'alert' column (which we will take care of)""
    #    'diaObject', 'diaSourcesList', 'diaForcedSourcesList', 'diaNondetectionLimitsList', 'annotations', 'ebv'
    json_df = pd.read_json(path)

    # 2. Make the latest_source_df 
    #    diaSourceList contains the diaSource table fields for each diaSource in a given diaObject/row
    #    the latest source is the last item. The easiest thing to do is extract the 1-row dataframe of the last source
    #    for each diaObjectId and collect them in a list to cocatenate at the end
    #    WARNING: CONCATENATION OF DATAFRAMES IN A LOOP IS SLOWER THAN THIS (because copies have to be made every time)

    latestSourceId_dfList = []
    objectIds_withoutAlert_col = []
    above_threshold_features_22 = [] # each item a tuple: is_above_flag, first_time_flag, n_above
    above_threshold_features_21 = []
    above_threshold_features_20 = []
    above_threshold_features_19 = []
    above_threshold_features_18 = []

    loop_index = 0  # INDEX FUCKERY IN HERE I HAVE TO KEEP TRACK, SEE EXPLANATION AT TOP OF FILE
    for i in range(json_df.shape[0]):
        try: 
            latestSourceId_dfList.append(pd.DataFrame(json_df['alert'].values[i]['diaSourcesList'][-1], 
                                                index=[0]))
            
            __lc = pd.DataFrame(json_df['alert'].values[i]['diaSourcesList'])

            above_threshold_features_22.append([loop_index]+ list(flux_threshold_features(__lc, 
                                                                    threshold_njy=mag_to_njy_thresholds['22'])))
            above_threshold_features_21.append([loop_index]+ list(flux_threshold_features(__lc, 
                                                                    threshold_njy=mag_to_njy_thresholds['21'])))
            above_threshold_features_20.append([loop_index]+ list(flux_threshold_features(__lc, 
                                                                    threshold_njy=mag_to_njy_thresholds['20'])))
            above_threshold_features_19.append([loop_index]+ list(flux_threshold_features(__lc, 
                                                                    threshold_njy=mag_to_njy_thresholds['19'])))
            above_threshold_features_18.append([loop_index]+ list(flux_threshold_features(__lc, 
                                                                    threshold_njy=mag_to_njy_thresholds['18'])))
            loop_index += 1
        except TypeError:
            loop_index += 1 # YES THIS IS CORRECT DO NOT REMOVE - see dev notes for explanation
            # this happens if the alert column for that row is NaN
            # if that happens, we have a problem and we need to log it
            objectIds_withoutAlert_col.append(json_df['diaObjectId'].values[i])


    # 3. Concatenate and set the index
    latestSourceIds_df = pd.concat(latestSourceId_dfList)

    # 4. Make the filter output df
    #    Take all rows (axis=0), and every column (axis=1) except the last one ('alert')
    filterOutput_df = json_df.iloc[:,:-1]

    # 5. Join our Lasair filter features to the lates diaSourceId features
    clean_df = latestSourceIds_df.join(filterOutput_df, lsuffix='_sourceId')

    # 6. Make the magnitude threshold flag feature dataframes
    #    The thresholds are for 22nd, 21st, 20th, 19th and 18th mag
    flags_22 = pd.DataFrame(above_threshold_features_22, columns=['index', 'is_above_22', 'first_time_22', 'N_above_22']).drop_duplicates()
    flags_21 = pd.DataFrame(above_threshold_features_21, columns=['index', 'is_above_21', 'first_time_21', 'N_above_21']).drop_duplicates()
    flags_20 = pd.DataFrame(above_threshold_features_20, columns=['index', 'is_above_20', 'first_time_20', 'N_above_20']).drop_duplicates()
    flags_19 = pd.DataFrame(above_threshold_features_19, columns=['index', 'is_above_19', 'first_time_19', 'N_above_19']).drop_duplicates()
    flags_18 = pd.DataFrame(above_threshold_features_18, columns=['index', 'is_above_18', 'first_time_18', 'N_above_18']).drop_duplicates()

    # 7. Join the flags to the clean_df
    clean_final = clean_df.join([flags_22.set_index('index'), 
                                flags_21.set_index('index'),
                                flags_20.set_index('index'),
                                flags_19.set_index('index'),
                                flags_18.set_index('index'),
                                ])

    return clean_final.reset_index(), objectIds_withoutAlert_col
